export { ROUNDONE_PROJECT_REF, supabase } from '../lib/supabase.ts'
export { verifySupabaseConnection, type ConnectionCheck } from './connection.ts'
export { TABLES, type TableName } from './tables.ts'
export {
  OAUTH_CALLBACK_PATH,
  authErrorMessage,
  claimInterviewerPersona,
  fullNameFromParts,
  getCurrentUser,
  isUnconfirmedEmailError,
  oauthRedirectErrorMessage,
  onAuthStateChange,
  requireUser,
  sendPasswordReset,
  resendSignupEmail,
  signInInterviewer,
  signInWithGoogle,
  signOut,
  signUpInterviewer,
  type AppRole,
  type SignInInput,
  type SignUpInterviewerInput,
  type SignUpResult,
} from './auth.ts'
export { getCurrentInterviewer, type InterviewerAccount } from './interviewer.ts'
export {
  applySignupProfile,
  getInterviewerProfile,
  getInterviewerRoles,
  getInterviewerSkills,
  getVerificationStatus,
  hydrateInterviewerSignupFromMetadata,
  isPlaceholderProfessional,
  profileCompleteness,
  updateInterviewerProfile,
  updateInterviewerRoles,
  updateInterviewerSkills,
  type DisplayVerificationStatus,
  type InterviewerProfileUpdates,
  type VerificationStatusItem,
} from './interviewerProfile.ts'
export {
  SERVICE_CURRENCY,
  SERVICE_DURATIONS,
  createService,
  deleteService,
  getMyServices,
  paiseToRupees,
  rupeesToPaise,
  setServiceActive,
  updateService,
  type CreateServiceInput,
  type InterviewerServiceRecord,
  type UpdateServiceInput,
} from './interviewerServices.ts'
export {
  BOOKING_BUFFER_MINUTES,
  createAvailability,
  createBlockedTime,
  createCustomSlot,
  deleteAvailability,
  deleteBlockedTime,
  deleteCustomSlot,
  getMyAvailability,
  getMyBlockedTimes,
  getMyBookingBuffer,
  getMyCustomSlots,
  getMyTimezone,
  loadMyAvailabilityBoard,
  updateAvailability,
  updateBlockedTime,
  updateCustomSlot,
  updateMyBookingBuffer,
  updateMyTimezone,
  type AvailabilityBoard,
  type AvailabilityWindow,
  type AvailabilityWindowInput,
  type AvailabilityWindowUpdates,
  type BlockedTimeInput,
  type BlockedTimeRecord,
  type BlockedTimeUpdates,
  type BookingBufferMinutes,
  type CustomSlotInput,
  type CustomSlotRecord,
  type CustomSlotUpdates,
  type Weekday,
} from './interviewerAvailability.ts'
export {
  BOOKING_ALREADY_UPDATED,
  bookingsForTab,
  confirmBooking,
  getCancelledBookings,
  getCompletedBookings,
  getMyBooking,
  getMyBookings,
  getPendingBookingRequests,
  getUpcomingBookings,
  isActionableBookingRequest,
  rejectBooking,
  tabForBooking,
  type DbBookingStatus,
  type InterviewerBooking,
  type InterviewerBookingCandidate,
  type InterviewerBookingTab,
} from './interviewerBookings.ts'
export {
  endInterviewSession,
  getInterviewSessionByBooking,
  getInterviewSessionsByBookingIds,
  interviewJoinState,
  loadMyInterviewBoard,
  startInterviewSession,
  type InterviewJoinState,
  type InterviewSessionBundle,
  type InterviewSessionRecord,
} from './interviewSessions.ts'
