export { ROUNDONE_PROJECT_REF, supabase } from '../lib/supabase.ts'
export { verifySupabaseConnection, type ConnectionCheck } from './connection.ts'
export { TABLES, type TableName } from './tables.ts'
export {
  OAUTH_CALLBACK_PATH,
  authErrorMessage,
  claimInterviewerPersona,
  fullNameFromParts,
  getCurrentUser,
  isUnconfirmedEmailError,
  oauthRedirectErrorMessage,
  onAuthStateChange,
  requireUser,
  sendPasswordReset,
  resendSignupEmail,
  signInInterviewer,
  signInWithGoogle,
  signOut,
  signUpInterviewer,
  type AppRole,
  type SignInInput,
  type SignUpInterviewerInput,
  type SignUpResult,
} from './auth.ts'
export { getCurrentInterviewer, type InterviewerAccount } from './interviewer.ts'
export {
  applySignupProfile,
  getInterviewerProfile,
  getInterviewerRoles,
  getInterviewerSkills,
  getVerificationStatus,
  getMyProfile,
  hydrateInterviewerSignupFromMetadata,
  isPlaceholderProfessional,
  isProfileSetupComplete,
  profileCompleteness,
  updateInterviewerProfile,
  updateInterviewerRoles,
  updateInterviewerSkills,
  type DisplayVerificationStatus,
  type InterviewerProfileUpdates,
  type VerificationStatusItem,
} from './interviewerProfile.ts'
export {
  SERVICE_CURRENCY,
  SERVICE_DURATIONS,
  createService,
  deleteService,
  getMyServices,
  paiseToRupees,
  rupeesToPaise,
  setServiceActive,
  updateService,
  type CreateServiceInput,
  type InterviewerServiceRecord,
  type UpdateServiceInput,
} from './interviewerServices.ts'
export {
  BOOKING_BUFFER_MINUTES,
  createAvailability,
  createBlockedTime,
  createCustomSlot,
  deleteAvailability,
  deleteBlockedTime,
  deleteCustomSlot,
  getMyAvailability,
  getMyBlockedTimes,
  getMyBookingBuffer,
  getMyCustomSlots,
  getMyTimezone,
  loadMyAvailabilityBoard,
  replaceMyCustomSlots,
  replaceMyWeeklyAvailability,
  updateAvailability,
  updateBlockedTime,
  updateCustomSlot,
  updateMyBookingBuffer,
  updateMyTimezone,
  type AvailabilityBoard,
  type AvailabilityWindow,
  type AvailabilityWindowInput,
  type AvailabilityWindowUpdates,
  type BlockedTimeInput,
  type BlockedTimeRecord,
  type BlockedTimeUpdates,
  type BookingBufferMinutes,
  type CustomSlotInput,
  type CustomSlotRecord,
  type CustomSlotUpdates,
  type Weekday,
} from './interviewerAvailability.ts'
export {
  BOOKING_ALREADY_UPDATED,
  bookingsForTab,
  cancelMyBooking,
  canCancelBooking,
  canRescheduleBooking,
  confirmBooking,
  getCancelledBookings,
  getCompletedBookings,
  getMyBooking,
  getMyBookings,
  getPendingBookingRequests,
  getUpcomingBookings,
  isActionableBookingRequest,
  listMyBookableSlots,
  listMyBookingsWithStatuses,
  rejectBooking,
  rescheduleMyBooking,
  tabForBooking,
  type DbBookingStatus,
  type InterviewerBooking,
  type InterviewerBookingCandidate,
  type InterviewerBookingTab,
} from './interviewerBookings.ts'
export {
  endInterviewSession,
  getInterviewSessionByBooking,
  getInterviewSessionsByBookingIds,
  interviewJoinState,
  loadMyInterviewBoard,
  startInterviewSession,
  type InterviewJoinState,
  type InterviewSessionBundle,
  type InterviewSessionRecord,
} from './interviewSessions.ts'
export {
  FEEDBACK_ALREADY_SUBMITTED,
  FEEDBACK_INVALID_SCORE,
  FEEDBACK_MISSING_FIELDS,
  FEEDBACK_NETWORK_ERROR,
  FEEDBACK_NOT_COMPLETED,
  FEEDBACK_UNAUTHORIZED,
  READINESS_LABELS,
  READINESS_LEVELS,
  canSubmitInterviewerFeedback,
  getFeedbackBookingIds,
  getMyFeedbackForBooking,
  interviewerFeedbackAction,
  isFeedbackScore,
  isReadinessLevel,
  submitInterviewerFeedback,
  validateFeedbackInput,
  type InterviewerFeedbackRecord,
  type ReadinessLevel,
  type SubmitInterviewerFeedbackInput,
} from './interviewerFeedback.ts'
export {
  countMyUnreadNotifications,
  listMyNotifications,
  loadMyNotificationBoard,
  markAllNotificationsRead,
  markNotificationRead,
  notificationHref,
  type InterviewerNotification,
  type NotificationBoard,
} from './interviewerNotifications.ts'
export {
  getMyNotificationPreferences,
  updateMyNotificationPreference,
  type NotificationPreferenceKey,
  type NotificationPreferences,
} from './interviewerNotificationPreferences.ts'
export {
  loadMyEarnings,
  netEarningsPaise,
  type EarningsBoard,
  type EarningsPeriod,
} from './interviewerEarnings.ts'
export {
  AUDIT_ACTIONS,
  AUDIT_ACTION_LABELS,
  AUDIT_ENTITY_LABELS,
  AUDIT_ENTITY_TYPES,
  auditDetails,
  listAdminAuditLogs,
  listAdminBookings,
  listAdminReviews,
  listAdminServices,
  listAdminVerifications,
  loadAdminDashboardMetrics,
  moderateAdminReview,
  setAdminServiceActive,
  updateAdminVerification,
  type AdminAuditAction,
  type AdminAuditEntityType,
  type AdminBookingFilter,
  type AdminModerationStatus,
  type AdminVerificationStatus,
} from './adminOperations.ts'
export {
  loadMyPublicReviewSummary,
  listMyPublicReviews,
  type PublicReviewPreview,
  type PublicReviewRecord,
  type PublicReviewSummary,
} from './interviewerReviews.ts'
export {
  activeServiceCount,
  buildDashboardAttentionItems,
  completedInterviewCount,
  interviewSessionStatusLabel,
  isAvailabilityConfigured,
  pendingBookingRequests,
  recentCompletedInterviews,
  upcomingInterviewCount,
  upcomingInterviews,
  verificationSummary,
  type DashboardAttentionItem,
} from './interviewerDashboard.ts'
export { getMyCandidate, listMyCandidates, type InterviewerCandidateHistory } from './interviewerCandidates.ts'
